services:
  db:
    image: postgres:15-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - marketplace

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - marketplace
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
volumes:
  db_data:
  static_volume:

networks:
  marketplace:
