version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - net

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapp
    command: /app/entrypoint.sh
    depends_on:
      - db
    networks:
      - net
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/src/static
    expose:
      - "8000"

volumes:
  db_data:
  static_volume:

networks:
  net:
